Get TopLevel mostly compiling + TopLevelRefinements mostly proven.
There appears to be an issue with extraction:

File "/home/calvin/git/vellvm/src/ml/extracted/Extract.v", line 81, characters 0-38:
Error: Anomaly "Uncaught exception Not_found."
Please report at http://coq.inria.fr/bugs/.

Other notes:

- Convert L3 -> L2 for most lemmas.
  + Had to comment out some related to memory.
     * ExpPure / lemmas involving memory instructions are the main
     casualties.
- Add Memory interpreter modules.
  + Missing link in TLR proof is the interp_memory_correct lemma here.